# Generated by Django 3.2.4 on 2021-10-31 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique='true')),
                ('slug', models.SlugField(max_length=200, unique='true')),
                ('img', models.ImageField(upload_to='photos')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technoapp.categ')),
            ],
        ),
    ]
