# Generated by Django 3.2.4 on 2021-10-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technoapp', '0002_mobiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobiles',
            old_name='name',
            new_name='mobname',
        ),
    ]
